---
title: "palmer_carbonate_qc"
author: "Kate Morkeski"
date: "r Sys.Date()"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load libraries and set path

```{r}

library(tidyverse)
library(readxl)
library(lubridate)
library(here)
library(egg)

here("palmer-carb-qc")

```
## Read in 2020 data

```{r}

pal2020 <- read_excel('LMG20-01_carbonate_summary.xlsx')

pal2020 <- pal2020 %>%
   rename(DIC_umolkg = "DIC_avg _umolkg-1",
         TA_umolkg = "TA_umolkg",
         Salinity_psu = "Salinity_to_use") 

pal2020 <- pal2020 %>%
  mutate(type = case_when(Depth != "underway" ~ "Niskin",
                          TRUE ~ Depth))  %>%
  mutate(depth = case_when(type == "underway" ~ "0",
                         TRUE ~ Depth))  

pal2020$depth <- as.numeric(pal2020$depth)

```

## Read in 2023 data

```{r}

pal2023 <- read_csv('LMG23-01_carbonate_summary.csv')

pal2023 <- pal2023 %>%
  rename(Salinity_psu = "Salinity_primary") %>%
  mutate(Date = mdy(Date))

pal2023 <- pal2023 %>%
  mutate(type = case_when(Depth != "UW" ~ "Niskin",
                          Depth == "UW" ~ "underway"
                          ))  %>%
  mutate(depth = case_when(Depth == "UW" ~ "0",
                         TRUE ~ Depth))  

pal2023$depth <- as.numeric(pal2023$depth)

```

## Read in 2024 data

```{r}

pal2024 <- read_csv('LMG24-01_carbonate_summary.csv')

pal2024 <- pal2024 %>%
  rename(Salinity_psu = "Salinity_primary") %>%
  mutate(Date = mdy(Date))

pal2024 <- pal2024 %>%
  mutate(type = case_when(Depth != "underway" ~ "Niskin",
                          Depth == "underway" ~ "underway"
                          ))  %>%
  mutate(depth = case_when(Depth == "underway" ~ "0",
                         TRUE ~ Depth))  

pal2024$depth <- as.numeric(pal2024$depth)

```
## Plot data

All samples

```{r}
  
plot1 <- ggplot(pal2020, aes(x= Salinity_psu, y = DIC_umolkg, color = type))+ geom_point()+labs(title = "LMG20-01")+theme(legend.position="none")
plot2 <- ggplot(pal2020, aes(x= Salinity_psu, y = TA_umolkg, color = type))+ geom_point()+theme(legend.position="top")
#ggplot(pal2020, aes(x= TA_umolkg, y = DIC_umolkg, color = type))+ geom_point()+labs(title = "LMG20-01")
plot3 <- ggplot(pal2020, aes(x= DIC_umolkg, y = -depth, color = type))+ geom_point()+theme(legend.position="none")
plot4 <- ggplot(pal2020, aes(x= TA_umolkg, y = -depth, color = type))+ geom_point()+theme(legend.position="none")
ggarrange(plot1, plot2, plot3, plot4, nrow = 2)
ggsave("LMG20-01.png")

plot1 <- ggplot(pal2023, aes(x= Salinity_psu, y = DIC_umolkg, color = type))+ geom_point()+labs(title = "LMG23-01")+theme(legend.position="none")
plot2 <- ggplot(pal2023, aes(x= Salinity_psu, y = TA_umolkg, color = type))+ geom_point()+theme(legend.position="top")
#ggplot(pal2023, aes(x= TA_umolkg, y = DIC_umolkg, color = type))+ geom_point()+labs(title = "LMG23-01")
plot3 <- ggplot(pal2023, aes(x= DIC_umolkg, y = -depth, color = type))+ geom_point()+theme(legend.position="none")
plot4 <- ggplot(pal2023, aes(x= TA_umolkg, y = -depth, color = type))+ geom_point()+theme(legend.position="none")
ggarrange(plot1, plot2, plot3, plot4, nrow = 2)
ggsave("LMG23-01.png")

plot1 <- ggplot(pal2024, aes(x= Salinity_psu, y = DIC_umolkg, color = type))+ geom_point()+labs(title = "LMG24-01")+theme(legend.position="none")
plot2 <- ggplot(pal2024, aes(x= Salinity_psu, y = TA_umolkg, color = type))+ geom_point()+theme(legend.position="top")
#ggplot(pal2024, aes(x= TA_umolkg, y = DIC_umolkg, color = type))+ geom_point()+labs(title = "LMG24-01")
plot3 <- ggplot(pal2024, aes(x= DIC_umolkg, y = -depth, color = type))+ geom_point()+theme(legend.position="none")
plot4 <- ggplot(pal2024, aes(x= TA_umolkg, y = -depth, color = type))+ geom_point()+theme(legend.position="none")
ggarrange(plot1, plot2, plot3, plot4, nrow = 2)
ggsave("LMG24-01.png")


```
Niskin samples

```{r}

ggplot(subset(pal2020, type == "Niskin"), aes(x= DIC_umolkg, y = -depth, color = Salinity_psu))+ geom_point() + scale_color_gradient(low="yellow", high="red")
ggplot(subset(pal2020, type == "Niskin"), aes(x= TA_umolkg, y = -depth, color = Salinity_psu))+ geom_point() + scale_color_gradient(low="yellow", high="red")

ggplot(subset(pal2020, type == "Niskin"), aes(x= Salinity_psu, y = DIC_umolkg, color = Event)) + geom_point() + scale_color_gradient(low="yellow", high="red")
ggplot(subset(pal2020, type == "Niskin"), aes(x= Salinity_psu, y = TA_umolkg, color = Event)) + geom_point() + scale_color_gradient(low="yellow", high="red")
ggplot(subset(pal2020, type == "Niskin"), aes(x= TA_umolkg, y = DIC_umolkg, color = Event)) + geom_point() + scale_color_gradient(low="yellow", high="red")

```

Surface Niskins

```{r}
# plot Niskin dic and ta vs depth, colored by event number
ggplot(subset(pal2020, type == "Niskin" & depth < 100), aes(x= DIC_umolkg, y = -depth, color = Event))+ geom_point() + scale_color_gradient(low="yellow", high="red")
ggplot(subset(pal2020, type == "Niskin" & depth < 100), aes(x= TA_umolkg, y = -depth, color = Event))+ geom_point() + scale_color_gradient(low="yellow", high="red")

# plot Niskin dic and ta vs event number 
# note large differences between some DIC replicates
ggplot(subset(pal2020, type == "Niskin" ), aes(x= Event, y = DIC_umolkg, color = depth))+ geom_point() + scale_color_gradient(low="orange", high="red")
ggplot(subset(pal2020, type == "Niskin" ), aes(x= Event, y = TA_umolkg, color = depth))+ geom_point() + scale_color_gradient(low="orange", high="red")

```

Underway samples

```{r}

ggplot(subset(pal2020, type == "underway"), aes(x= Salinity_psu, y = DIC_umolkg, color = Event))+ geom_point() 
ggplot(subset(pal2020, type == "underway"), aes(x= Station, y = DIC_umolkg))+ geom_point()
+ scale_color_gradient(low="aquamarine1", high="aquamarine4")
ggplot(subset(pal2020, type == "underway"), aes(x= Salinity_psu, y = TA_umolkg, color = Event))+ geom_point() + scale_color_gradient(low="aquamarine1", high="aquamarine4")

```
## Read in, clean, and plot historical data

```{r}

# run knb-lter-pal.44.8.r downloaded from the EDI Data Portal
# temporal coverage 1993-2019

source("knb-lter-pal.44.8.r")

historical <- dt1 

historical <- historical %>%
  mutate(DIC1 = replace(DIC1, DIC1 <0, NA)) %>%  ## to replace -9.0
  mutate(Alkalinity2 = replace(Alkalinity2, Alkalinity2 <0, NA)) %>%  ## to replace -999 
  mutate(Salinity = replace(Salinity, Salinity < 0, NA))  ## to replace -999

# examine outlying values
lowalk <- subset(historical, Alkalinity1 < 2000 | Alkalinity2 < 2000) # note one observation Alkalinity.1 = 10 umol/kg
lowdic <- subset(historical, DIC1 < 1800 | DIC2 < 1800)
lowsal <- subset(historical, Salinity < 1)

# prepare for plotting

# rename columns to match pal2020
historical <- historical %>% 
    rename(Salinity_psu = Salinity,
           DIC_umolkg = DIC1,
           TA_umolkg = Alkalinity1) %>% 
    mutate(type = "historical") 

historical <- historical %>% 
    mutate(year = year(DatetimeGMT))

historical$year <- as.factor(historical$year)

# eliminate some oddly low values from 1996 
# one low alkalinity of 10, two samples with DIC of 1212 and 1225 umol/kg
historical <- historical %>% 
    filter (TA_umolkg > 10) %>%
    filter (DIC_umolkg > 1500)

histund <- historical %>% filter(BottleNumber == "UW")
histNiskin <- historical %>% filter(BottleNumber != "UW")
```


```{r} 

# plot dic and ta 
# note: plotting only DIC1, and Alkalinity1, not DIC2 and Alkalinity2
ggplot(historical, aes(x= Salinity_psu, y = DIC_umolkg, color = -Depth))+ geom_point()
ggplot(historical, aes(x= Salinity_psu, y = TA_umolkg, color = -Depth))+ geom_point()

ggplot(historical, aes(x= DIC_umolkg, y = -Depth, color = Salinity_psu))+ geom_point()
ggplot(historical, aes(x= TA_umolkg, y = -Depth, color = Salinity_psu))+ geom_point()

ggplot(historical, aes(x= DIC_umolkg, y = -Depth, color = year))+ geom_point()
ggplot(historical, aes(x= TA_umolkg, y = -Depth, color = year))+ geom_point()

ggplot(historical, aes(x= Salinity_psu, y = DIC_umolkg, color = year))+ geom_point()+scale_fill_discrete(year)
ggplot(historical, aes(x= Salinity_psu, y = TA_umolkg, color = year))+ geom_point()

ggplot(histund, aes(x= Salinity_psu, y = DIC_umolkg, color = year))+ geom_point()+scale_fill_discrete(year)
ggplot(histund, aes(x= NominalStation, y = DIC_umolkg, color = year))+ geom_point()+scale_fill_discrete(year)
ggplot(histund, aes(x= year, y = DIC_umolkg, color = year))+ geom_point()+scale_fill_discrete(year)

ggplot(histNiskin, aes(x= DIC_umolkg, y = -Depth, color = Salinity_psu))+ geom_point()
ggplot(histNiskin, aes(x= TA_umolkg, y = -Depth, color = Salinity_psu))+ geom_point()

```

## Plot 2020 and historical data

```{r}

# plot historical and 2020 dic and ta vs salinity, colored by type (historical, Niskin 2020, underway 2020)
ggplot(historical, aes(x= Salinity_psu, y = DIC_umolkg, color = type))+ geom_point() +geom_point(data = pal2020 )
ggplot(historical, aes(x= Salinity_psu, y = TA_umolkg, color = type))+ geom_point() +geom_point(data = pal2020 )

```
# Examine replicates

```{r}

replicates <- read_excel("LMG20-01_carbonate_replicates.xlsx")

ggplot(replicates, aes(x= DIC_avg_umolkg, y = DIC_diff_replicates, color = Depth))+ geom_point()
ggplot(replicates, aes(x= TA_umolkg, y = TA_diff_replicates, color = Depth))+ geom_point()

```

